:LATEX_PROPERTIES:
#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [a4paper, notitlepage]

#+LATEX_HEADER: \usepackage{polyglossia}
#+LATEX_HEADER: \setmainlanguage{greek}
#+LATEX_HEADER: \setotherlanguage{english}

#+LATEX_HEADER: \usepackage{microtype}

#+LATEX_HEADER: \usepackage{newcomputermodern}

#+LATEX_HEADER: \usepackage{biblatex}

#+LATEX_HEADER: \usepackage[margin=1.3in]{geometry}

#+LATEX_HEADER: \renewcommand{\baselinestretch}{1.2}

#+LATEX_HEADER: \usemintedstyle{friendly}
#+LATEX_HEADER: \setminted{frame=single, framesep=2mm}

#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \rhead{ΥΣΒΔ}
#+LATEX_HEADER: \lhead{\textit{Εργασίες 1 \& 2}}

#+LATEX_HEADER: \usepackage{titlesec}
#+LATEX_HEADER: \titleformat{\section}{\large \center \bf \uppercase}{\thesection}{0.5em}{}{}
:END:
#+TITLE: Υλοποίηση Συστημάτων Βάσεων Δεδομένων
#+SUBTITLE: Εργασίες 1 & 2
#+AUTHOR: Κωνσταντίνος Χούσος @@latex:\\ \small{ΑΜ: 1115202000215} \and@@
#+AUTHOR: Αναστάσιος-Φαίδων Σεϊτανίδης @@latex:\\ \small{ΑΜ: 1115202000179}@@
#+OPTIONS: num:nil toc:nil date:nil timestamp:nil
#+STARTUP: overview

* Εργασία 1

** Αρχείο Σωρού

*** Συναρτήσεις

Οι παρακάτω συναρτήσεις εκμεταλλεύονται τις συναρτήσεις επιπέδου block =BF_*= για την υλοποίησή τους, προσθέτοντας ωστόσο παραπάνω λειτουργικότητα.

- =HP_CreateFile=: Δημιουργεί το αρχείο με όνομα =filename=, δημιουργεί το block 0 κι αρχικοποιεί τις τιμές του όσον αφορά τα =HP_info= και =HP_block_info=. Κάνει το block 0 dirty και το κάνει unpin. Τέλος, κλείνει το αρχείο.
- =HP_OpenFile=: Ανοίγει το αρχείο σωρού με όνομα =filename=. Ελέγχει αν το αρχείο πρόκειται για αρχείο κατακερματισμού ή όχι. Αν όχι, συνεχίζει. Καθώς κάθε φορά που καλείται η =BF_OpenFile= το =fileDesc= αλλάζει, ενημερώνουμε κάθε φορά το =HP_info= του block 0. Κάνουμε dirty κι unpin το block 0, κρατώντας ωστόσο το =HP_info= στον σωρό κι επιστρέφοντάς το.
- =HP_CloseFile=: Βρίσκει πόσα blocks έχει το αρχείο σωρού. Σε ένα for loop κάνει το καθένα unpin. Κλείνει το αρχείο κι αποδεσμεύει την μνήμη του =HP_info= που υπάρχει στον σωρό.
- =HP_InsertEntry=: Βρίσκει το τελευταίο block του αρχείου σωρού. Ελέγχει αν υπάρχει αρκετός χώρος σε αυτό για την εγγραφή μιας πλειάδας. Αν ναι, αντιγράφει την πλειάδα σε αυτό. Αν όχι, δημιουργεί ένα νέο block στο τέλος του αρχείου σωρού, γράφει σε αυτό την πλειάδα και αρχικοποιεί τα metadata του. Έπειτα ενημερώνει το =HP_info= για το νέο block και το κάνει unpin. Τέλος, επιστρέφει τον αναγνωριστικό αριθμό του block στο οποίο έγινε τελικά η εγγραφή.
- =HP_GetAllEntries=: Η συνάρτηση επιστρέφει μία μεταβλητή =int read_blocks=. Αυτή αρχικοποιείται με -1 και ανανεώνεται όταν βρούμε ένα record με id =​= value. Αν επιστραφεί και δεν έχει αλλάξει, σημαίνει πως υπήρξε κάποιο σφάλμα.  Διατρέχει όλα τα blocks του αρχείου σωρού, βρίσκει για το καθένα πόσες εγγραφές υπάρχουν και τυπώνει αυτές που έχουν id == value.

*** Δομή Αρχείου Σωρού

**** Δομή =HP_info=

Ένα αρχείο σωρού χαρακτηρίζεται από τα εξής στοιχεία:
- =int fileDesc=: Ο αναγνωριστικός αριθμός ανοίγματος αρχείου από το επίπεδο block
- =int lastBlockDesc=: Ο αναγνωριστικός αριθμός του τελευταίου σε αριθμό block του αρχείου σωρού
- =int isHT=: Ένα flag που δηλώνει αν το αρχείο είναι αρχείο κατακερματισμού ή όχι. Στην περίπτωση του αρχείου σωρού αρχικοποιείται με 0.

**** Δομή =HP_block_info=

Ένα block ενός αρχείου σωρού χαρακτηρίζεται από τα εξής στοιχεία:
- =int blockDesc=: Ο αναγνωριστικός αριθμός του block στην αρίθμηση των block του αρχείου σωρού
- =int recsNum=: Το πλήθος εγγεγραμμένων πλειάδων στο συγκεκριμένο block
- =int nextBlock=: Ο αναγνωριστικός αριθμός του επόμενου block στην αρίθμηση των block του αρχείου σωρού.

*** Σημειώσεις

Το =HP_ERROR= ορίζεται σε -1, καθώς δεν έχει αρχικοποιηθεί κι αλλιώς δεν δουλεύει η συνάρτηση =CALL_BF=.

* COMMENT Σημειώσεις
** DONE "Ιδανικά θέλουμε το block αυτό να παραμένει στην ενδιάμεση μνήμη και να γίνει unpin με το κλείσιμο του αρχείου"
CLOSED: [2023-01-08 Sun 20:18]
** TODO έλεγχος για αρχείο κατακερματισμού
** TODO Στα μεταδεδομένα block (HT_block_info) ο κάδος 9 θα πρέπει να δείχνει τον κάδο 1 που περιέχει επίσης δεδομένα του ίδιου κάδου

* COMMENT Local Variables
# Local Variables:
# org-latex-hyperref-template: "\\hypersetup{pdfauthor={Κωνσταντίνος Χούσος, Αναστάσιος-Φαίδων Σεϊτανίδης},pdftitle={%t},pdfkeywords={%k},pdfsubject={%d},pdfcreator={%c}, pdflang={%L},colorlinks,linkcolor=blue,citecolor=red,urlcolor=blue}"
# End:
